const express = require('express');
const cors = require('cors');
const { corsOrigin } = require('./config/env');
const { AppError } = require('./utils/http');
const authRoutes = require('./routes/v1/auth');
const catalogRoutes = require('./routes/v1/catalog');
const staffRoutes = require('./routes/v1/staff');
const patientRoutes = require('./routes/v1/patients');
const appointmentRoutes = require('./routes/v1/appointments');
const clinicalRoutes = require('./routes/v1/clinical');
const financeRoutes = require('./routes/v1/finance');
const publicBookingRoutes = require('./routes/v1/public-booking');

const app = express();
app.disable('x-powered-by');
app.use((req, res, next) => { res.setHeader('X-Content-Type-Options', 'nosniff'); res.setHeader('X-Frame-Options', 'DENY'); res.setHeader('Referrer-Policy', 'no-referrer'); res.setHeader('Permissions-Policy', 'camera=(), microphone=(), geolocation=()'); next(); });
app.use(cors({ origin: corsOrigin.split(',').map((origin) => origin.trim()), methods: ['GET', 'POST', 'PATCH'], allowedHeaders: ['Content-Type', 'Authorization'] }));
app.use(express.json({ limit: '100kb' }));
app.get('/health', (req, res) => res.json({ status: 'ok', service: 'careflow-clinic-api' }));
app.use('/api/v1/auth', authRoutes);
app.use('/api/v1/catalog', catalogRoutes);
app.use('/api/v1/staff', staffRoutes);
app.use('/api/v1/clinical', clinicalRoutes);
app.use('/api/v1/finance', financeRoutes);
app.use('/api/v1', patientRoutes);
app.use('/api/v1', appointmentRoutes);
app.use('/api/v1/public/booking', publicBookingRoutes);
app.use((req, res, next) => next(new AppError(404, 'Route not found.')));
app.use((error, req, res, next) => { const status = error.statusCode || (error.name === 'ValidationError' ? 422 : error.code === 11000 ? 409 : 500); if (status >= 500) console.error(error); res.status(status).json({ error: { message: status >= 500 ? 'Unexpected server error.' : error.message, ...(error.details ? { details: error.details } : {}) } }); });
module.exports = app;
