import { useEffect, useState } from 'react';
import PropTypes from 'prop-types';
import { EmailAuthProvider, onAuthStateChanged, reauthenticateWithCredential, signOut, updatePassword, updateProfile } from 'firebase/auth';
import { Link, Navigate } from 'react-router-dom';
import { auth } from '../lib/firebase';

const AccountSettings = ({ staff = false }) => {
  const [user, setUser] = useState(undefined); const [title, setTitle] = useState(''); const [displayName, setDisplayName] = useState(''); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  useEffect(() => onAuthStateChanged(auth, (next) => { setUser(next || null); const existing = next?.displayName || ''; const match = existing.match(/^(Dr\.|Mr\.|Mrs\.|Ms\.)\s+(.*)$/); setTitle(match?.[1] || ''); setDisplayName(match?.[2] || existing); }), []);
  const updateName = async (event) => { event.preventDefault(); setError(''); try { const fullName = `${title ? `${title} ` : ''}${displayName.trim()}`.trim(); await updateProfile(user, { displayName: fullName }); setNotice('Your profile name was updated.'); } catch { setError('Unable to update your profile.'); } };
  const changePassword = async (event) => { event.preventDefault(); setError(''); setNotice(''); if (newPassword.length < 6) { setError('Use a password with at least six characters.'); return; } try { const credential = EmailAuthProvider.credential(user.email, currentPassword); await reauthenticateWithCredential(user, credential); await updatePassword(user, newPassword); setCurrentPassword(''); setNewPassword(''); setNotice('Your password has been changed.'); } catch { setError('We could not change the password. Check your current password and try again.'); } };
  if (user === undefined) return <main className="staff-shell"><p className="workspace-status">Loading your account…</p></main>;
  if (!user) return <Navigate to={staff ? '/staff/login' : '/login'} replace />;
  const back = staff ? '/staff' : '/patient';
  return <main className="staff-shell"><header className="staff-topbar"><div><Link to="/" className="staff-wordmark">SOOD CLINIC</Link><span>{staff ? 'Staff / My account' : 'Patient / My account'}</span></div><nav><Link to={back}>Back to workspace</Link><button type="button" onClick={() => signOut(auth)}>Sign out</button></nav></header><div className="account-settings"><header><p className="section-kicker">Account security</p><h1>My account</h1><span>Update your profile name or securely manage your password.</span></header>{notice && <p className="admin-notice" role="status">{notice}</p>}{error && <p className="staff-login__error" role="alert">{error}</p>}<section className="account-settings__grid"><form className="admin-panel admin-form" onSubmit={updateName}><div><p className="section-kicker">Profile</p><h2>How we address you</h2></div><label>Email<input value={user.email || ''} disabled /></label><label>Title<select value={title} onChange={(event) => setTitle(event.target.value)}><option value="">No title</option><option>Dr.</option><option>Mr.</option><option>Mrs.</option><option>Ms.</option></select></label><label>Full name<input value={displayName} onChange={(event) => setDisplayName(event.target.value)} placeholder="Your first and last name" required /></label><button type="submit">Save profile</button></form><form className="admin-panel admin-form" onSubmit={changePassword}><div><p className="section-kicker">Password</p><h2>Change password</h2><span>Enter your current password to choose a new one.</span></div><label>Current password<input type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} required autoComplete="current-password" /></label><label>New password<input type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} minLength="6" required autoComplete="new-password" /></label><button type="submit">Change password</button><Link className="account-reset-button" to={`/reset-password${staff ? '?staff=1' : ''}`}>Email me a reset link instead</Link></form></section></div></main>;
};
AccountSettings.propTypes = { staff: PropTypes.bool };
export default AccountSettings;
