import { useEffect, useState } from 'react';
import PropTypes from 'prop-types';
import { EmailAuthProvider, onAuthStateChanged, reauthenticateWithCredential, sendPasswordResetEmail, signOut, updatePassword, updateProfile } from 'firebase/auth';
import { Link, Navigate } from 'react-router-dom';
import NotificationMenu from '../components/NotificationMenu';
import { auth } from '../lib/firebase';

const AccountSettings = ({ staff = false }) => {
  const [user, setUser] = useState(undefined); const [view, setView] = useState('overview'); const [title, setTitle] = useState(''); const [displayName, setDisplayName] = useState(''); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  useEffect(() => onAuthStateChanged(auth, (next) => { setUser(next || null); const existing = next?.displayName || ''; const match = existing.match(/^(Dr\.|Mr\.|Mrs\.|Ms\.)\s+(.*)$/); setTitle(match?.[1] || ''); setDisplayName(match?.[2] || existing); }), []);
  const updateName = async (event) => { event.preventDefault(); setError(''); try { await updateProfile(user, { displayName: `${title ? `${title} ` : ''}${displayName.trim()}`.trim() }); setNotice('Profile updated.'); setView('overview'); } catch { setError('We could not update your profile.'); } };
  const sendReset = async () => { setError(''); try { await sendPasswordResetEmail(auth, user.email); setNotice('A password-reset link was sent to your email.'); setView('overview'); } catch { setError('We could not send a reset link. Please try again.'); } };
  const changePassword = async (event) => { event.preventDefault(); setError(''); if (newPassword.length < 10) { setError('Use a password with at least 10 characters.'); return; } try { await reauthenticateWithCredential(user, EmailAuthProvider.credential(user.email, currentPassword)); await updatePassword(user, newPassword); setCurrentPassword(''); setNewPassword(''); setNotice('Password changed.'); setView('overview'); } catch { setError('Check your current password and try again.'); } };
  if (user === undefined) return <main className="staff-shell"><p className="workspace-status">Loading…</p></main>;
  if (!user) return <Navigate to={staff ? '/staff/login' : '/login'} replace />;
  const back = staff ? '/staff' : '/patient';
  return <main className="staff-shell"><header className="staff-topbar"><Link to="/" className="staff-wordmark">SOOD CLINIC</Link><nav><NotificationMenu /><Link to={back}>Back</Link><button type="button" onClick={() => signOut(auth)}>Sign out</button></nav></header><div className="account-settings"><header><h1>{view === 'profile' ? 'Edit profile' : view === 'security' ? 'Password & sign-in' : 'Account'}</h1></header>{notice && <p className="admin-notice" role="status">{notice}</p>}{error && <p className="staff-login__error" role="alert">{error}</p>}{view === 'overview' && <section className="account-settings__grid"><button className="admin-panel admin-form" type="button" onClick={() => setView('profile')}><h2>Edit profile</h2><span>Personal details</span></button><button className="admin-panel admin-form" type="button" onClick={() => setView('security')}><h2>Password & sign-in</h2><span>Manage your password</span></button></section>}{view === 'profile' && <form className="admin-panel admin-form account-settings__single" onSubmit={updateName}><label>Email<input value={user.email || ''} disabled /></label><label>Title<select value={title} onChange={(event) => setTitle(event.target.value)}><option value="">No title</option><option>Dr.</option><option>Mr.</option><option>Mrs.</option><option>Ms.</option></select></label><label>Full name<input value={displayName} onChange={(event) => setDisplayName(event.target.value)} placeholder="Your full name" required /></label><div className="account-settings__actions"><button type="button" className="staff-secondary-button" onClick={() => setView('overview')}>Cancel</button><button type="submit">Save changes</button></div></form>}{view === 'security' && <section className="account-settings__grid"><form className="admin-panel admin-form" onSubmit={changePassword}><h2>Change password</h2><label>Current password<input type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} required autoComplete="current-password" /></label><label>New password<input type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} minLength="10" required autoComplete="new-password" /></label><button type="submit">Change password</button></form><section className="admin-panel admin-form"><h2>Forgot password?</h2><span>We will email you a secure reset link.</span><button type="button" onClick={sendReset}>Send reset link</button><button type="button" className="staff-secondary-button" onClick={() => setView('overview')}>Back</button></section></section>}</div></main>;
};
AccountSettings.propTypes = { staff: PropTypes.bool };
export default AccountSettings;
