import { useCallback, useEffect, useMemo, useState } from 'react';
import { onAuthStateChanged, signOut } from 'firebase/auth';
import { httpsCallable } from 'firebase/functions';
import { Link, Navigate } from 'react-router-dom';
import NotificationMenu from '../components/NotificationMenu';
import { auth, functions } from '../lib/firebase';

const readableAction = (action) => String(action || 'activity_recorded').replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const readableResource = (resourceType) => String(resourceType || 'system').replaceAll('_', ' ');
const formatTime = (value) => value ? new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Kolkata' }).format(new Date(value)) : 'Timestamp pending';

const AdminAudit = () => {
  const [access, setAccess] = useState('checking'); const [events, setEvents] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [filters, setFilters] = useState({ action: '', role: '', resource: '' });
  const load = useCallback(async () => { setLoading(true); setError(''); try { const result = await httpsCallable(functions, 'getAuditLog')({ limit: 50 }); setEvents(result.data.events || []); } catch (caught) { setError(caught?.message || 'The activity log could not be loaded.'); } finally { setLoading(false); } }, []);
  useEffect(() => onAuthStateChanged(auth, async (user) => { if (!user) return setAccess('signed-out'); const token = await user.getIdTokenResult(); setAccess(token.claims.forcePasswordChange ? 'password-change' : token.claims.role === 'admin' ? 'allowed' : 'denied'); }), []);
  useEffect(() => { if (access === 'allowed') load(); }, [access, load]);
  const options = useMemo(() => ({ actions: [...new Set(events.map((event) => event.action))].sort(), roles: [...new Set(events.map((event) => event.actorRole))].sort(), resources: [...new Set(events.map((event) => event.resourceType))].sort() }), [events]);
  const visibleEvents = useMemo(() => events.filter((event) => (!filters.action || event.action === filters.action) && (!filters.role || event.actorRole === filters.role) && (!filters.resource || event.resourceType === filters.resource)), [events, filters]);
  if (access === 'signed-out') return <Navigate to="/staff/login" replace />;
  if (access === 'password-change') return <Navigate to="/staff/account" replace />;
  if (access === 'denied') return <main className="staff-shell"><section className="workspace-gate"><p>SOOD CLINIC STAFF</p><h1>Administrator access required</h1><button type="button" onClick={() => signOut(auth)}>Sign out</button></section></main>;
  if (access === 'checking') return <main className="staff-shell"><p className="workspace-status">Verifying secure administrator access…</p></main>;
  return <main className="staff-shell"><header className="staff-topbar"><Link to="/staff/admin" className="staff-wordmark">SOOD CLINIC</Link><nav><Link to="/staff/admin">Overview</Link><Link to="/staff/admin/patients">Patients</Link><Link to="/staff/admin/catalogue">Booking setup</Link><Link to="/staff/admin/access">Staff access</Link><Link to="/staff/admin/audit" className="is-active">Activity</Link><NotificationMenu /><Link to="/staff/account">My account</Link><button type="button" onClick={() => signOut(auth)}>Sign out</button></nav></header><div className="admin-audit"><header className="staff-access__heading"><div><p className="section-kicker">Governance</p><h1>Activity log</h1><span>Latest protected operational events. This view intentionally excludes patient details and other sensitive audit metadata.</span></div><button type="button" onClick={load} disabled={loading}>{loading ? 'Refreshing…' : 'Refresh'}</button></header>{error && <p className="staff-login__error" role="alert">{error}</p>}<section className="admin-panel audit-log"><div className="admin-panel__head"><div><p className="section-kicker">Latest activity</p><h2>Operational events</h2></div><span>{visibleEvents.length} of {events.length}</span></div>{!loading && events.length > 0 && <div className="audit-log__filters"><label>Action<select value={filters.action} onChange={(event) => setFilters({ ...filters, action: event.target.value })}><option value="">All actions</option>{options.actions.map((action) => <option key={action} value={action}>{readableAction(action)}</option>)}</select></label><label>Role<select value={filters.role} onChange={(event) => setFilters({ ...filters, role: event.target.value })}><option value="">All roles</option>{options.roles.map((role) => <option key={role} value={role}>{role}</option>)}</select></label><label>Resource<select value={filters.resource} onChange={(event) => setFilters({ ...filters, resource: event.target.value })}><option value="">All resources</option>{options.resources.map((resource) => <option key={resource} value={resource}>{readableResource(resource)}</option>)}</select></label><button type="button" onClick={() => setFilters({ action: '', role: '', resource: '' })}>Clear</button></div>}{loading ? <p className="empty-state">Loading protected activity…</p> : visibleEvents.length ? <ul>{visibleEvents.map((event) => <li key={event.id}><time dateTime={event.at || undefined}>{formatTime(event.at)}</time><div><strong>{readableAction(event.action)}</strong><span>{readableResource(event.resourceType)} · performed by {event.actorRole}</span></div></li>)}</ul> : <p className="empty-state">{events.length ? 'No activity matches these filters.' : 'No recent activity is available.'}</p>}</section></div></main>;
};

export default AdminAudit;
