import { useEffect, useState } from 'react';
import { onAuthStateChanged, signOut } from 'firebase/auth';
import { collection, doc, onSnapshot, orderBy, query, updateDoc, writeBatch } from 'firebase/firestore';
import { Link, Navigate } from 'react-router-dom';
import { auth, firestore } from '../lib/firebase';
import { toIstParts } from '../lib/ist';

const greeting = () => { const { hour } = toIstParts(new Date()); return hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening'; };
const ReceptionWorkspace = () => {
  const [state, setState] = useState('checking'); const [user, setUser] = useState(null); const [appointments, setAppointments] = useState([]); const [notice, setNotice] = useState('');
  useEffect(() => onAuthStateChanged(auth, async (next) => { if (!next) { setState('signed-out'); return; } const token = await next.getIdTokenResult(); setUser(next); setState(token.claims.role === 'receptionist' ? 'allowed' : 'denied'); }), []);
  useEffect(() => { if (state !== 'allowed') return undefined; return onSnapshot(query(collection(firestore, 'appointments'), orderBy('startsAt', 'asc')), (snapshot) => setAppointments(snapshot.docs.map((item) => ({ id: item.id, ...item.data() }))), () => setNotice('Appointments could not be loaded.')); }, [state]);
  const updateStatus = async (appointment, status) => { try { if (status === 'cancelled') { const batch = writeBatch(firestore); batch.update(doc(firestore, 'appointments', appointment.id), { status, updatedAt: new Date().toISOString(), updatedBy: user.uid }); batch.update(doc(firestore, 'appointmentSlots', appointment.slotId), { status: 'available', appointmentId: null, updatedAt: new Date().toISOString() }); await batch.commit(); } else { await updateDoc(doc(firestore, 'appointments', appointment.id), { status, updatedAt: new Date().toISOString(), updatedBy: user.uid }); } setNotice(`Appointment marked ${status}.`); } catch { setNotice('Unable to update this appointment.'); } };
  if (state === 'signed-out') return <Navigate to="/staff/login" replace />;
  if (state === 'denied') return <main className="staff-shell"><section className="workspace-gate"><p>SOOD CLINIC STAFF</p><h1>Reception access required</h1><span>This account is not assigned the reception role.</span><button className="staff-secondary-button" type="button" onClick={() => signOut(auth)}>Sign out</button></section></main>;
  if (state === 'checking') return <main className="staff-shell"><p className="workspace-status">Verifying staff access…</p></main>;
  const current = appointments.filter((item) => item.status === 'scheduled' || item.status === 'confirmed'); const name = user?.displayName || 'Reception team member';
  return <main className="staff-shell"><header className="staff-topbar"><div><Link to="/" className="staff-wordmark">SOOD CLINIC</Link><span>Staff / Reception</span></div><nav><Link to="/staff/reception" className="is-active">Appointments</Link><Link to="/">View public site</Link><button type="button" onClick={() => signOut(auth)}>Sign out</button></nav></header><div className="staff-admin"><header className="staff-admin__heading"><div><p className="section-kicker">Reception desk</p><h1>{greeting()}, {name}</h1><span>Today’s patient schedule at a glance.</span></div><div className="staff-admin__identity"><strong>{current.length} active appointments</strong><span>Confirm arrivals and keep the queue accurate.</span></div></header>{notice && <p className="admin-notice" role="status">{notice}</p>}<section className="admin-panel admin-panel--appointments reception-queue"><div className="admin-panel__head"><div><p className="section-kicker">Patient queue</p><h2>Appointments</h2></div><Link to="/Booknow">New booking</Link></div><div className="admin-appointment-list">{appointments.length ? appointments.map((appointment) => <article className="admin-appointment" key={appointment.id}><div><strong>{appointment.patient?.name || 'Patient'}</strong><span>{new Date(appointment.startsAt).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}</span><small>{appointment.patient?.phone || 'No phone number'} · {appointment.reason || 'Consultation'}</small></div><div><span className={`appointment-status appointment-status--${appointment.status}`}>{appointment.status}</span>{['scheduled', 'confirmed'].includes(appointment.status) && <div className="admin-appointment__actions">{appointment.status === 'scheduled' && <button type="button" onClick={() => updateStatus(appointment, 'confirmed')}>Confirm</button>}<button type="button" onClick={() => updateStatus(appointment, 'checked-in')}>Check in</button><button type="button" className="button-danger" onClick={() => updateStatus(appointment, 'cancelled')}>Cancel</button></div>}</div></article>) : <p className="empty-state">No appointments are booked yet.</p>}</div></section></div></main>;
};
export default ReceptionWorkspace;
